package io.ssafy.mogeun.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFDA574)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFF4ED)
val md_theme_light_onPrimaryContainer = Color(0xFF331200)
val md_theme_light_secondary = Color(0xFF334FD8)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF00105A)
val md_theme_light_tertiary = Color(0xFF55D631)
val md_theme_light_onTertiary = Color(0x11000000)
val md_theme_light_tertiaryContainer = Color(0xFF99E6A5)
val md_theme_light_onTertiaryContainer = Color(0xFFF5D4B1)
val md_theme_light_error = Color(0xFFBB1614)
val md_theme_light_errorContainer = Color(0xFFE49494)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFFFF3E7)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_outline = Color(0xFF847469)
val md_theme_light_inverseOnSurface = Color(0xFFF8EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB68F)
val md_theme_light_surfaceTint = Color(0xFF974812)
val md_theme_light_outlineVariant = Color(0xFFD6C3B6)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF8F2)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFF3DFD2)
val md_theme_light_onSurfaceVariant = Color(0xFF51443B)

val md_theme_dark_primary = Color(0xFFFFB68F)
val md_theme_dark_onPrimary = Color(0xFF542100)
val md_theme_dark_primaryContainer = Color(0xFF773200)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBCA)
val md_theme_dark_secondary = Color(0xFFBAC3FF)
val md_theme_dark_onSecondary = Color(0xFF00208F)
val md_theme_dark_secondaryContainer = Color(0xFF0E33C0)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE0FF)
val md_theme_dark_tertiary = Color(0xFF23E19C)
val md_theme_dark_onTertiary = Color(0xFF003824)
val md_theme_dark_tertiaryContainer = Color(0xFF005235)
val md_theme_dark_onTertiaryContainer = Color(0xFF52FEB7)
val md_theme_dark_error = Color(0xFFFFB4A9)
val md_theme_dark_errorContainer = Color(0xFF930005)
val md_theme_dark_onError = Color(0xFF690002)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD5)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE9E1D9)
val md_theme_dark_outline = Color(0xFF9E8E82)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D9)
val md_theme_dark_inversePrimary = Color(0xFF974812)
val md_theme_dark_surfaceTint = Color(0xFFFFB68F)
val md_theme_dark_outlineVariant = Color(0xFF51443B)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF16130E)
val md_theme_dark_onSurface = Color(0xFFCDC5BD)
val md_theme_dark_surfaceVariant = Color(0xFF51443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C3B6)


val seed = Color(0xFFFDA574)
