pipeline {
    environment {
        docker_repo = "gugaro/hkdream"
        docker_key = credentials("Docker")
        docker_image = ''
    }
    agent any
    stages {
        stage('Build Android Client') {
            steps {
                sh '''
                    cd ./Application/Mogeun/
                    chmod 777 ./gradlew
                    ./gradlew assembleDebug
                '''
            }
        }
        stage('Deploy on FireBase') {
            steps {
                sh '''
                    cd ./Application/Mogeun
                    chmod 777 ./gradlew
                    ./gradlew appDistributionUploadDebug
                '''
            }
        }
    }
    post {
        success {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'good', 
                message: "빌드 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)", 
                endpoint: 'https://meeting.ssafy.com/hooks/ii4u9h3fzff9tpqmndkh7hwq7w',
                channel: 'C104-Jenkins'
                )
            }
        }
        failure {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'danger', 
                message: "빌드 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)", 
                endpoint: 'https://meeting.ssafy.com/hooks/ii4u9h3fzff9tpqmndkh7hwq7w',
                channel: 'C104-Jenkins'
                )
            }
        }
    }
}
