spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://k9c104.p.ssafy.io:3306/muscle
    username: [mogeun-server-username]
    password: [mogeun-server-password]
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    #    defer-datasource-initialization: true
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: k9c104.p.ssafy.io
    port: 6379
